package artillects.core;

import java.io.File;
import java.util.Arrays;

import net.minecraft.server.MinecraftServer;
import net.minecraftforge.common.Configuration;
import calclavia.lib.config.Config;
import calclavia.lib.content.IDManager;
import calclavia.lib.utility.LanguageUtility;
import cpw.mods.fml.common.FMLCommonHandler;
import cpw.mods.fml.common.Loader;
import cpw.mods.fml.common.ModMetadata;

/** @author Darkguardsman */
public class Settings
{
    public static final Configuration CONFIGURATION = new Configuration(new File(Loader.instance().getConfigDir(), Reference.NAME + ".cfg"));

    /** IDs suggested by Jyzarc and Horfius */
    public static final IDManager idManager;

    static
    {
        CONFIGURATION.load();
        idManager = new IDManager(CONFIGURATION.get(Configuration.CATEGORY_GENERAL, "BlockIDPrefix", 1700).getInt(1700), CONFIGURATION.get(Configuration.CATEGORY_GENERAL, "ItemIDPrefix", 20150).getInt(20150));
        CONFIGURATION.save();
    }

    public static int getNextBlockID()
    {
        return idManager.getNextBlockID();
    }

    public static int getNextBlockID(String key)
    {
        int id = idManager.getNextBlockID();
        return Settings.CONFIGURATION.get(Configuration.CATEGORY_BLOCK, key, id).getInt(id);
    }

    public static int getNextItemID()
    {
        return idManager.getNextItemID();
    }

    public static int getNextItemID(String key)
    {
        int id = idManager.getNextItemID();
        return Settings.CONFIGURATION.get(Configuration.CATEGORY_ITEM, key, id).getInt(id);
    }

    public static void setModMetadata(ModMetadata metadata, String id, String name)
    {
        setModMetadata(metadata, id, name, "");
    }

    public static void setModMetadata(ModMetadata metadata, String id, String name, String parent)
    {
        metadata.modId = id;
        metadata.name = name;
        metadata.description = LanguageUtility.getLocal("meta.artillects.description");
        metadata.url = "no site";
        metadata.logoFile = "artillects_logo.png";
        metadata.version = Reference.VERSION + "." + Reference.BUILD_VERSION;
        metadata.authorList = Arrays.asList(new String[] { "DarkCow", "Calclavia", "Archadia" });
        metadata.credits = LanguageUtility.getLocal("meta.artillects.credits");
        metadata.parent = parent;
        metadata.autogenerated = false;
    }

    public static boolean isOp(String username)
    {
        MinecraftServer theServer = FMLCommonHandler.instance().getMinecraftServerInstance();

        if (theServer != null)
        {
            return theServer.getConfigurationManager().getOps().contains(username.trim().toLowerCase());
        }

        return false;
    }
}
